# Generated by Django 3.1.2 on 2020-10-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados',
            name='casos',
            field=models.CharField(max_length=200, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='mortes',
            field=models.CharField(max_length=200, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='novos_casos',
            field=models.CharField(max_length=200, verbose_name='Estado'),
        ),
    ]
