# Generated by Django 3.1.2 on 2020-10-22 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201021_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datahora_atualizacao', models.DateTimeField(verbose_name='Data de atualização')),
            ],
        ),
    ]
